### ISSUE TITLE
Add new date/calendar methods that allow specifying a timezone.

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf-docs#32]
As per the commit to fix https://github.com/thymeleaf/thymeleaf/issues/64

**Comment by simonered** [comment]
any news?

**Comment by ultraq** [comment]
Oh man, I totally forgot about this issue!

Source files for Thymeleaf 2.1 and 3.0 docs have been updated, I'll just ping @danielfernandez now to ask to generate the docs for all the formats we support.

**Comment by simonered** [comment]
Thank you!

**Comment by danielfernandez** [comment]
Pong! :) Published.
