### ISSUE TITLE
Links in Interactive Tutorial do not work

### ISSUE THREAD

**Issue by tokorhon** [thymeleaf/thymeleaf-docs#38]
Links to manual do not work. E.g. http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#keeping-iteration-status in  Exercise 7 does not go to  "chapter 6 - section 2 of the Using Thymeleaf" but in "404 File not found".

**Comment by jmiguelsamper** [comment]
Hello,

thank you very much for the report, some time ago the structure of the documentation changed on the Thymeleaf website. I've just fixed the links.

Regards.
