### ISSUE TITLE
"Using Thymeleaf" guide for 3.0 refers to XHTML and HTML5 modes

### ISSUE THREAD

**Issue by Medo42** [thymeleaf/thymeleaf-docs#43]
This is in chapter 15.1 "Template Resolvers"
It is probably an oversight from adapting the document for 3.0, since as I understand there is now only one HTML mode.

**Comment by Medo42** [comment]
As an extra nitpick, the section has the text "Thymeleaf includes three other implementations out of the box" and then goes on to describe four ;)

**Comment by ultraq** [comment]
Good finds! 👍
