### ISSUE TITLE
UsingThymeleaf 3.0 "Appendix C" chapter number should be 20

### ISSUE THREAD

**Issue by bufferings** [thymeleaf/thymeleaf-docs#48]
docs/tutorials/3.0/usingthymeleaf.md

currently

```
19 Appendix B: Expression Utility Objects
19 Appendix C: Markup Selector Syntax
```

so, it should be

```
19 Appendix B: Expression Utility Objects
20 Appendix C: Markup Selector Syntax
```

BTW, I will start translating UsingThymeleaf 3.0 into Japanese :)

**Comment by ultraq** [comment]
Whoops, looks like we can't count! 😝  Thanks for pointing this out.

**Comment by danielfernandez** [comment]
Yup, docs were regenerated last night :)
