### ISSUE TITLE
Using Thymeleaf 4.15 is before 4.14

### ISSUE THREAD

**Issue by bufferings** [thymeleaf/thymeleaf-docs#60]
I think the numbering order is wrong ;)

4.15 Data Conversion / Formatting
https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#data-conversion-formatting

4.14 Preprocessing
https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#preprocessing

![screenshot from 2018-04-30 20-46-39](https://user-images.githubusercontent.com/763849/39425720-a52058a8-4cb7-11e8-978b-0ac21987fa76.png)

**Comment by ultraq** [comment]
Yup, definitely wrong! 😆  Will fix soon.  Thanks for letting us know!
