### ISSUE TITLE
Typo in docs: "emtpy" instead of "empty"

### ISSUE THREAD

**Issue by samorajp** [thymeleaf/thymeleaf-docs#71]
Hi, 
I have found two occurrences of "emtpy" in fragment below:

> Advanced conditional insertion of fragments
> 
> The availability of both the emtpy fragment and no-operation token allows us to perform conditional insertion of fragments in a very easy and elegant way.
> 
> For example, we could do this in order to insert our common :: adminhead fragment only if the user is an administrator, and insert nothing (emtpy fragment) if not:

Here is PR with fix: https://github.com/thymeleaf/thymeleaf-docs/pull/70

**Comment by ultraq** [comment]
Fixed in the linked PR.
