### ISSUE TITLE
Japanese translations for 3.1/usingthymeleaf.md and thymeleaf31whatsnew.md

### ISSUE THREAD

**Issue by MasatoshiTada** [thymeleaf/thymeleaf-docs#90]
I'm one of the Japanese translators of ["Using Thymeleaf (ja)"](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf_ja.html) for Thymeleaf 3.0.

I'd like to contribute again to the Japanese translation of Thymeleaf 3.1 documents.
I'm translating 3.1/usingthymeleaf.md and thymeleaf31whatsnew.md and @bufferings is reviewing them.
(repository -> https://github.com/thymeleaf-docs-ja/thymeleaf-docs/tree/docs-ja-develop )

I'd like you to publish 3.1/usingthymeleaf_ja.md in [thymeleaf.org](http://thymeleaf.org/) as same as 3.0 after finishing the translation.
But, how about thymeleaf31whatsnew_ja.md? Can you publish it in [thymeleaf.org](http://thymeleaf.org/) as same as usingthymeleaf_ja.md?
If you cannot, can I publish it in my own blog?
Japanese translation of this migration guide will be very helpful for Japanese developers.

Please give it some consideration.

**Comment by ultraq** [comment]
Hi there, sorry for taking so long to get back to you, but yes we would be happy to host a Japanese translation of both of these documents on thymeleaf.org

Feel free to submit a pull request with the translation when you're ready, and I can merge that then generate all the necessary HTML files to add to the Thymeleaf website 😊

**Comment by MasatoshiTada** [comment]
Thank you so much!
We'll send a PR after finishing translation😃

**Comment by MasatoshiTada** [comment]
Sorry for being late! We finally finished the translation and sent a PR.
Please take a look😃
