### ISSUE TITLE
Layout collapses in usingthymeleaf.html

### ISSUE THREAD

**Issue by MasatoshiTada** [thymeleaf/thymeleaf-docs#94]
# What happens
I have layout collapses around 5.3 and 5.6 in usingthymeleaf.html (see screenshots below). 

<img width="1424" alt="screenshot_01" src="https://github.com/thymeleaf/thymeleaf-docs/assets/7044137/75f9a2d8-474b-4f54-a427-100a1676a56a">

<img width="1440" alt="screenshot_02" src="https://github.com/thymeleaf/thymeleaf-docs/assets/7044137/cef336f5-354b-408e-9223-c5b5b87702d1">

# How to reproduce
1. `brew install pandoc`
2. `./gradlew clean generateDocsHTML`

# Environment
```shell
$ ./gradlew --version

------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17 (Oracle Corporation 17+35-2724)
OS:           Mac OS X 13.6 x86_64
```

**Comment by mikoto2000** [comment]
The behavior seems to have changed after updating pandoc.

I couldn't reproduce it with pandoc version 2.9.2.1, but I did reproduce it with version 3.1.8.

([homebrew default version is 3.1.8](https://formulae.brew.sh/formula/pandoc#default), [Ubuntu 20.04 apt default version is 2.9.2.1.](https://packages.ubuntu.com/jammy/pandoc))

**Comment by MasatoshiTada** [comment]
@mikoto2000 Thank you so much!
I installed 2.9.2.1 and I could get non-collapsed HTML😆
I tried three versions below:

- 2.9.2.1 -> OK
- 2.19.2 -> NG
- 3.1.8 -> NG

**Comment by MasatoshiTada** [comment]
@ultraq I'd like to send a PR for the Japanese translation of usingthymeleaf.md and thymeleaf31whatsnew.md.
Can I send a PR in this situation? usingthymeleaf_ja.md has the same problem.

**Comment by mikoto2000** [comment]
After Pandoc 3, need blank line between html and markdown.

https://github.com/thymeleaf/thymeleaf-docs/blob/d760571cc36d371bed311fcc0a226d2acebd9a39/docs/tutorials/3.1/usingthymeleaf.md?plain=1#L1889-L1890

to

```md
 <div class="table-scroller"> 

 ------------------- ------------------ ------------------ 
```

and

https://github.com/thymeleaf/thymeleaf-docs/blob/d760571cc36d371bed311fcc0a226d2acebd9a39/docs/tutorials/3.1/usingthymeleaf.md?plain=1#L1899-L1900

to

```md
 ------------------- ------------------ ------------------ 

 </div> 
```

**Comment by MasatoshiTada** [comment]
Thank you for your advice, but unfortunately, it doesn't work on my PC😭
I still have the same problem on pandoc 3.1.8.

**Comment by MasatoshiTada** [comment]
@ultraq Thanks to @mikoto2000 , I could get non-collapsed HTMLs on pandoc 3.1.8!
May I send a PR to fix this problem?
It works on both pandoc 3.1.8 and 2.9.2.1.

**Comment by ultraq** [comment]
Yep, a PR that fixes this up would be great, thank you 👍

**Comment by MasatoshiTada** [comment]
@ultraq Thanks! I sent a PR. Please take a look.
https://github.com/thymeleaf/thymeleaf-docs/pull/95
